name: mobile_aanext
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  provider: ^6.1.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.5.3
  flutter_dotenv: ^6.0.0
  flutter_secure_storage : ^8.0.0
  share_plus: ^7.2.1
  audioplayers: ^5.2.1
  material: ^1.0.0+2
  visibility_detector: ^0.4.0+2
  foundation: ^0.0.5
  url_launcher: ^6.2.2
  web_socket_channel: ^2.4.0
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/aa_logo.png
    - .env
